.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MKM4V" "1" "April 2012" "ByHoffman" "mkm4v Manual"
.
.SH "NAME"
\fBmkm4v\fR \- make m4v files for Apple TV
.
.SH "SYNOPSIS"
\fBmkm4v\fR \fIoptions\fR \-i \fIfilename\fR [filename \.\.\.]
.
.SH "DESCRIPTION"
\fBmkm4v\fR automates the process of converting movies and tv shows for viewing on the Apple TV\. This process involves the conversion of DTS tracks to AC3, scanning of forced subtitle tracks, and automatic inclusion of subtitles when audio is not native language\.
.
.SH "OPTIONS"
.
.TP
\fB\-i\fR, \fB\-\-input\fR
List of files to be batch converted from source format to m4v container\.
.
.SH "COPYRIGHT"
mkm4v is Copyright (C) 2010 Chris Hoffman <byhoffman\.com>
.
.SH "SEE ALSO"
mkvmerge(1)
