.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "MKM4V" "1" "March 2010" "ByHoffman" "mkm4v Manual"
.
.SH "NAME"
\fBmkm4v\fR \-\- make m4v files for Apple TV
.
.SH "SYNOPSIS"
\fBmkm4v\fR [options] \fIfilename\fR [...]
.
.SH "DESCRIPTION"
\fBmkm4v\fR automates the process of converting movies and tv shows for
viewing on the Apple TV.  This process involves the conversion of
DTS tracks to AC3, scanning of forced subtitle tracks, and automatic
inclusion of subtitles when audio is not native language.
.
.SH "COPYRIGHT"
mkm4v is Copyright (C) 2010 Chris Hoffman <byhoffman.com>
.
.SH "SEE ALSO"
mkvmerge(1)
